baseURL = "https://cam-inc.github.io/viron-doc/"
languageCode = "en-us"
title = "Viron"
theme = "hyde"

[params]
  description = "TODO: description"
  copyright = "TODO: copyright"
  layoutReverse = true
